# Generated by Django 5.2.15 on 2026-06-15 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('settings_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(choices=[('zh', 'Chinese'), ('en', 'English')], default='zh', max_length=5)),
                ('seat_index', models.PositiveSmallIntegerField()),
                ('is_host', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('replay_pending', 'Replay Pending'), ('closed', 'Closed')], default='waiting', max_length=20)),
                ('game_type', models.CharField(choices=[('cooperative', 'Cooperative'), ('competitive', 'Competitive')], max_length=20)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.match')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='catalog.gamemode')),
                ('host_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to='rooms.player')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='catalog.theme')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='match',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rooms.room'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('hints', 'Hints'), ('guessing', 'Guessing'), ('judging', 'Judging'), ('rating', 'Rating'), ('settlement', 'Settlement'), ('complete', 'Complete')], default='hints', max_length=20)),
                ('is_coop_success', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rooms.match')),
            ],
            options={
                'db_table': 'rounds',
                'ordering': ['round_number'],
                'unique_together': {('match', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='rooms.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='rooms.round')),
            ],
            options={
                'db_table': 'hints',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_skipped', models.BooleanField(default=False)),
                ('verdict', models.CharField(choices=[('pending', 'Pending'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guessed_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='rooms.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='rooms.round')),
            ],
            options={
                'db_table': 'guesses',
                'unique_together': {('round', 'player')},
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='rooms.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='rooms.player')),
            ],
            options={
                'db_table': 'match_scores',
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='catalog.character')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.player')),
            ],
            options={
                'db_table': 'match_player_assignments',
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='HintRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('hint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rooms.hint')),
                ('rater_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_ratings', to='rooms.player')),
            ],
            options={
                'db_table': 'hint_ratings',
                'unique_together': {('hint', 'rater_player')},
            },
        ),
        migrations.CreateModel(
            name='GuessVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rooms.guess')),
                ('voter_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_votes', to='rooms.player')),
            ],
            options={
                'db_table': 'guess_votes',
                'unique_together': {('guess', 'voter_player')},
            },
        ),
        migrations.CreateModel(
            name='ReplayVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_votes', to='rooms.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_votes', to='rooms.player')),
            ],
            options={
                'db_table': 'replay_votes',
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'seat_index')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('room', 'match_number')},
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('breakdown', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_scores', to='rooms.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rooms.round')),
            ],
            options={
                'db_table': 'round_scores',
                'unique_together': {('round', 'player')},
            },
        ),
    ]
