# Generated by Django 5.2.15 on 2026-06-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='guess_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='guess',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
