# Generated by Django 5.2.15 on 2026-06-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_guess_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorHintRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('author_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_hint_ratings_received', to='rooms.player')),
                ('rater_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_hint_ratings_given', to='rooms.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_hint_ratings', to='rooms.round')),
            ],
            options={
                'db_table': 'author_hint_ratings',
                'unique_together': {('round', 'author_player', 'rater_player')},
            },
        ),
    ]
