# Generated by Django 5.2.15 on 2026-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_author_hint_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='guess_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
