# Generated by Django 5.2.15 on 2026-06-16 07:51

import apps.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_backfill_guess_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guess_history',
            field=models.JSONField(blank=True, default=apps.rooms.models.default_guess_history),
        ),
    ]
