# Generated by Django 5.2.15 on 2026-06-16 07:56

import apps.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_guess_history_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='assignments_snapshot',
            field=models.JSONField(blank=True, default=apps.rooms.models.default_assignments_snapshot),
        ),
    ]
