# Generated by Django 5.2.15 on 2026-06-15 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'game_modes',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='catalog.gamemode')),
            ],
            options={
                'db_table': 'themes',
                'unique_together': {('game_mode', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='catalog.theme')),
            ],
            options={
                'db_table': 'characters',
                'indexes': [models.Index(fields=['theme', 'is_active'], name='characters_theme_i_312c0e_idx')],
            },
        ),
    ]
